[project]
name = "redistricting-project"
version = "0.1.0"
description = "A ready-to-run redistricting analysis project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "binary-ensemble>=2.0",
    "click",
    "gerrychain>=1.0.0",
    "gerrytools>=2.0.1",
    "ipykernel",
    "ipywidgets",
    "joblib",
    "joblib-progress",
    "matplotlib",
    "maup",
    "numpy",
    "pandas",
]

[dependency-groups]
dev = [
    "ruff",
    "ty",
    "pyright"
]
